// Tarot Card Data - 78 cards total
// Images from Rider-Waite-Smith deck (Public Domain)
const tarotCards = [
    // Major Arcana (22 cards)
    { id: 0, name: "The Fool", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar00.jpg", upright: "New beginnings, innocence, spontaneity, free spirit", reversed: "Recklessness, taken advantage of, inconsideration" },
    { id: 1, name: "The Magician", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar01.jpg", upright: "Manifestation, resourcefulness, power, inspired action", reversed: "Manipulation, poor planning, untapped talents" },
    { id: 2, name: "The High Priestess", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar02.jpg", upright: "Intuition, sacred knowledge, divine feminine, subconscious mind", reversed: "Secrets, disconnected from intuition, withdrawal" },
    { id: 3, name: "The Empress", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar03.jpg", upright: "Femininity, beauty, nature, nurturing, abundance", reversed: "Creative block, dependence on others" },
    { id: 4, name: "The Emperor", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar04.jpg", upright: "Authority, establishment, structure, father figure", reversed: "Domination, excessive control, lack of discipline" },
    { id: 5, name: "The Hierophant", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar05.jpg", upright: "Spiritual wisdom, religious beliefs, conformity, tradition", reversed: "Personal beliefs, freedom, challenging the status quo" },
    { id: 6, name: "The Lovers", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar06.jpg", upright: "Love, harmony, relationships, values alignment, choices", reversed: "Self-love, disharmony, imbalance, misalignment of values" },
    { id: 7, name: "The Chariot", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar07.jpg", upright: "Control, willpower, success, action, determination", reversed: "Self-discipline, opposition, lack of direction" },
    { id: 8, name: "Strength", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar08.jpg", upright: "Strength, courage, persuasion, influence, compassion", reversed: "Inner strength, self-doubt, low energy, raw emotion" },
    { id: 9, name: "The Hermit", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar09.jpg", upright: "Soul searching, introspection, being alone, inner guidance", reversed: "Isolation, loneliness, withdrawal" },
    { id: 10, name: "Wheel of Fortune", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar10.jpg", upright: "Good luck, karma, life cycles, destiny, turning point", reversed: "Bad luck, resistance to change, breaking cycles" },
    { id: 11, name: "Justice", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar11.jpg", upright: "Justice, fairness, truth, cause and effect, law", reversed: "Unfairness, lack of accountability, dishonesty" },
    { id: 12, name: "The Hanged Man", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar12.jpg", upright: "Pause, surrender, letting go, new perspectives", reversed: "Delays, resistance, stalling, indecision" },
    { id: 13, name: "Death", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar13.jpg", upright: "Endings, change, transformation, transition", reversed: "Resistance to change, personal transformation, inner purging" },
    { id: 14, name: "Temperance", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar14.jpg", upright: "Balance, moderation, patience, purpose", reversed: "Imbalance, excess, self-healing, re-alignment" },
    { id: 15, name: "The Devil", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar15.jpg", upright: "Shadow self, attachment, addiction, restriction, sexuality", reversed: "Releasing limiting beliefs, exploring dark thoughts, detachment" },
    { id: 16, name: "The Tower", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar16.jpg", upright: "Sudden change, upheaval, chaos, revelation, awakening", reversed: "Personal transformation, fear of change, averting disaster" },
    { id: 17, name: "The Star", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar17.jpg", upright: "Hope, faith, purpose, renewal, spirituality", reversed: "Lack of faith, despair, self-trust, disconnection" },
    { id: 18, name: "The Moon", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar18.jpg", upright: "Illusion, fear, anxiety, subconscious, intuition", reversed: "Release of fear, repressed emotion, inner confusion" },
    { id: 19, name: "The Sun", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar19.jpg", upright: "Positivity, fun, warmth, success, vitality", reversed: "Inner child, feeling down, overly optimistic" },
    { id: 20, name: "Judgement", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar20.jpg", upright: "Judgement, rebirth, inner calling, absolution", reversed: "Self-doubt, inner critic, ignoring the call" },
    { id: 21, name: "The World", suit: "Major Arcana", image: "https://sacred-texts.com/tarot/pkt/img/ar21.jpg", upright: "Completion, integration, accomplishment, travel", reversed: "Seeking personal closure, short-cuts, delays" },

    // Wands (14 cards)
    { id: 22, name: "Ace of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/waac.jpg", upright: "Inspiration, new opportunities, growth, potential", reversed: "An emerging idea, lack of direction, distractions" },
    { id: 23, name: "Two of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa02.jpg", upright: "Future planning, progress, decisions, discovery", reversed: "Personal goals, inner alignment, fear of unknown" },
    { id: 24, name: "Three of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa03.jpg", upright: "Progress, expansion, foresight, overseas opportunities", reversed: "Playing small, lack of foresight, unexpected delays" },
    { id: 25, name: "Four of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa04.jpg", upright: "Celebration, joy, harmony, relaxation, homecoming", reversed: "Personal celebration, inner harmony, conflict with others" },
    { id: 26, name: "Five of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa05.jpg", upright: "Conflict, disagreements, competition, tension, diversity", reversed: "Inner conflict, conflict avoidance, tension release" },
    { id: 27, name: "Six of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa06.jpg", upright: "Success, public recognition, progress, self-confidence", reversed: "Private achievement, personal definition of success, fall from grace" },
    { id: 28, name: "Seven of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa07.jpg", upright: "Challenge, competition, protection, perseverance", reversed: "Exhaustion, giving up, overwhelmed" },
    { id: 29, name: "Eight of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa08.jpg", upright: "Movement, fast paced change, action, alignment, air travel", reversed: "Delays, frustration, resisting change, internal alignment" },
    { id: 30, name: "Nine of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa09.jpg", upright: "Resilience, courage, persistence, test of faith, boundaries", reversed: "Inner resources, struggle, overwhelm, defensive" },
    { id: 31, name: "Ten of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wa10.jpg", upright: "Burden, extra responsibility, hard work, completion", reversed: "Doing it all, carrying the burden, delegation, release" },
    { id: 32, name: "Page of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wapa.jpg", upright: "Inspiration, ideas, discovery, limitless potential, free spirit", reversed: "Newly-formed ideas, redirecting energy, self-limiting beliefs" },
    { id: 33, name: "Knight of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/wakn.jpg", upright: "Energy, passion, inspired action, adventure, impulsiveness", reversed: "Passion project, haste, scattered energy, delays" },
    { id: 34, name: "Queen of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/waqu.jpg", upright: "Courage, confidence, independence, social butterfly, determination", reversed: "Self-respect, self-confidence, introverted, re-establish sense of self" },
    { id: 35, name: "King of Wands", suit: "Wands", image: "https://sacred-texts.com/tarot/pkt/img/waki.jpg", upright: "Natural-born leader, vision, entrepreneur, honour", reversed: "Impulsiveness, haste, ruthless, high expectations" },

    // Cups (14 cards)
    { id: 36, name: "Ace of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cuac.jpg", upright: "Love, new relationships, compassion, creativity", reversed: "Self-love, intuition, repressed emotions" },
    { id: 37, name: "Two of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu02.jpg", upright: "Unified love, partnership, mutual attraction", reversed: "Self-love, break-ups, disharmony, distrust" },
    { id: 38, name: "Three of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu03.jpg", upright: "Celebration, friendship, creativity, collaborations", reversed: "Independence, alone time, hardcore partying, 'three's a crowd'" },
    { id: 39, name: "Four of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu04.jpg", upright: "Meditation, contemplation, apathy, reevaluation", reversed: "Retreat, withdrawal, checking in for alignment" },
    { id: 40, name: "Five of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu05.jpg", upright: "Regret, failure, disappointment, pessimism", reversed: "Personal setbacks, self-forgiveness, moving on" },
    { id: 41, name: "Six of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu06.jpg", upright: "Revisiting the past, childhood memories, innocence, joy", reversed: "Living in the past, forgiveness, lacking playfulness" },
    { id: 42, name: "Seven of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu07.jpg", upright: "Opportunities, choices, wishful thinking, illusion", reversed: "Alignment, personal values, overwhelmed by choices" },
    { id: 43, name: "Eight of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu08.jpg", upright: "Disappointment, abandonment, withdrawal, escapism", reversed: "Trying one more time, indecision, aimless drifting" },
    { id: 44, name: "Nine of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu09.jpg", upright: "Contentment, satisfaction, gratitude, wish come true", reversed: "Inner happiness, materialism, dissatisfaction" },
    { id: 45, name: "Ten of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cu10.jpg", upright: "Divine love, blissful relationships, harmony, alignment", reversed: "Disconnection, misaligned values, struggling relationships" },
    { id: 46, name: "Page of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cupa.jpg", upright: "Creative opportunities, intuitive messages, curiosity, possibility", reversed: "New ideas, doubting intuition, creative blocks" },
    { id: 47, name: "Knight of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cukn.jpg", upright: "Creativity, romance, charm, imagination, beauty", reversed: "Overactive imagination, unrealistic, jealous, moody" },
    { id: 48, name: "Queen of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cuqu.jpg", upright: "Compassionate, caring, emotionally stable, intuitive, in flow", reversed: "Inner feelings, self-care, self-love, co-dependency" },
    { id: 49, name: "King of Cups", suit: "Cups", image: "https://sacred-texts.com/tarot/pkt/img/cuki.jpg", upright: "Emotionally balanced, compassionate, diplomatic", reversed: "Self-compassion, inner feelings, moodiness, emotionally manipulative" },

    // Swords (14 cards)
    { id: 50, name: "Ace of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/swac.jpg", upright: "Breakthroughs, new ideas, mental clarity, success", reversed: "Inner clarity, re-thinking an idea, clouded judgement" },
    { id: 51, name: "Two of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw02.jpg", upright: "Difficult decisions, weighing up options, an impasse, avoidance", reversed: "Indecision, confusion, information overload, stalemate" },
    { id: 52, name: "Three of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw03.jpg", upright: "Heartbreak, emotional pain, sorrow, grief, hurt", reversed: "Negative self-talk, releasing pain, optimism, forgiveness" },
    { id: 53, name: "Four of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw04.jpg", upright: "Rest, relaxation, meditation, contemplation, recuperation", reversed: "Exhaustion, burn-out, deep contemplation, stagnation" },
    { id: 54, name: "Five of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw05.jpg", upright: "Conflict, disagreements, competition, defeat, winning at all costs", reversed: "Reconciliation, making amends, past resentment" },
    { id: 55, name: "Six of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw06.jpg", upright: "Transition, change, rite of passage, releasing baggage", reversed: "Personal transition, resistance to change, unfinished business" },
    { id: 56, name: "Seven of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw07.jpg", upright: "Betrayal, deception, getting away with something, acting strategically", reversed: "Imposter syndrome, self-deceit, keeping secrets" },
    { id: 57, name: "Eight of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw08.jpg", upright: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality", reversed: "Self-limiting beliefs, inner critic, releasing negative thoughts" },
    { id: 58, name: "Nine of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw09.jpg", upright: "Anxiety, worry, fear, depression, nightmares", reversed: "Inner turmoil, deep-seated fears, secrets, releasing anguish" },
    { id: 59, name: "Ten of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/sw10.jpg", upright: "Painful endings, deep wounds, betrayal, loss, crisis", reversed: "Recovery, regeneration, resisting an inevitable end" },
    { id: 60, name: "Page of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/swpa.jpg", upright: "New ideas, curiosity, thirst for knowledge, new ways of communicating", reversed: "Self-expression, all talk and no action, haphazard action" },
    { id: 61, name: "Knight of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/swkn.jpg", upright: "Ambitious, action-oriented, driven to succeed, fast-thinking", reversed: "Restless, unfocused, impulsive, burn-out" },
    { id: 62, name: "Queen of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/swqu.jpg", upright: "Independent, unbiased judgement, clear boundaries, direct communication", reversed: "Overly-emotional, easily influenced, bitchy, cold-hearted" },
    { id: 63, name: "King of Swords", suit: "Swords", image: "https://sacred-texts.com/tarot/pkt/img/swki.jpg", upright: "Mental clarity, intellectual power, authority, truth", reversed: "Quiet power, inner truth, misuse of power, manipulation" },

    // Pentacles (14 cards)
    { id: 64, name: "Ace of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/peac.jpg", upright: "A new financial or career opportunity, manifestation, abundance", reversed: "Lost opportunity, lack of planning and foresight" },
    { id: 65, name: "Two of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe02.jpg", upright: "Multiple priorities, time management, prioritisation, adaptability", reversed: "Over-committed, disorganisation, reprioritisation" },
    { id: 66, name: "Three of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe03.jpg", upright: "Teamwork, collaboration, learning, implementation", reversed: "Disharmony, misalignment, working alone" },
    { id: 67, name: "Four of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe04.jpg", upright: "Saving money, security, conservatism, scarcity, control", reversed: "Over-spending, greed, self-protection" },
    { id: 68, name: "Five of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe05.jpg", upright: "Financial loss, poverty, lack mindset, isolation, worry", reversed: "Recovery from financial loss, spiritual poverty" },
    { id: 69, name: "Six of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe06.jpg", upright: "Giving, receiving, sharing wealth, generosity, charity", reversed: "Self-care, unpaid debts, one-sided charity" },
    { id: 70, name: "Seven of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe07.jpg", upright: "Long-term view, sustainable results, perseverance, investment", reversed: "Lack of long-term vision, limited success or reward" },
    { id: 71, name: "Eight of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe08.jpg", upright: "Apprenticeship, repetitive tasks, mastery, skill development", reversed: "Self-development, perfectionism, misdirected activity" },
    { id: 72, name: "Nine of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe09.jpg", upright: "Abundance, luxury, self-sufficiency, financial independence", reversed: "Self-worth, over-investment in work, hustling" },
    { id: 73, name: "Ten of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pe10.jpg", upright: "Wealth, financial security, family, long-term success, contribution", reversed: "The dark side of wealth, financial failure or loss" },
    { id: 74, name: "Page of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pepa.jpg", upright: "Manifestation, financial opportunity, skill development", reversed: "Lack of progress, procrastination, learn from failure" },
    { id: 75, name: "Knight of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pekn.jpg", upright: "Hard work, productivity, routine, conservatism", reversed: "Self-discipline, boredom, feeling 'stuck', perfectionism" },
    { id: 76, name: "Queen of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/pequ.jpg", upright: "Nurturing, practical, providing financially, a working parent", reversed: "Financial independence, self-care, work-home conflict" },
    { id: 77, name: "King of Pentacles", suit: "Pentacles", image: "https://sacred-texts.com/tarot/pkt/img/peki.jpg", upright: "Wealth, business, leadership, security, discipline, abundance", reversed: "Financially inept, obsessed with wealth and status" }
];

// Celtic Cross positions and their meanings
const celticCrossPositions = [
    { position: 1, name: "Present Situation", description: "The current state of affairs" },
    { position: 2, name: "Challenge", description: "The immediate challenge or obstacle" },
    { position: 3, name: "Distant Past", description: "Foundation and deeper influences" },
    { position: 4, name: "Recent Past", description: "Events that have just passed" },
    { position: 5, name: "Best Outcome", description: "The best that can be achieved" },
    { position: 6, name: "Immediate Future", description: "What is approaching in the near future" },
    { position: 7, name: "Internal Factors", description: "Your attitude and internal state" },
    { position: 8, name: "External Factors", description: "Environmental influences and other people" },
    { position: 9, name: "Hopes and Fears", description: "Your hopes, fears, and expectations" },
    { position: 10, name: "Final Outcome", description: "The ultimate outcome and resolution" }
];
